WPF - Re-Added the resize hack for issue 2779
cefsharp/CefSharp pull request #4307
Opened 2022-11-16 13:20 UTC by Wupval

**Fixes:**
   - Fixes issue 4274

**Summary:**
   - Re-Added the resize hack for issue 2779, as the issue still occurs. Disabled by default as mentioned by @amaitland in https://github.com/cefsharp/CefSharp/discussions/4274#discussioncomment-3946056

**Changes:**
   - Re-Added the resize hack for issue 2779
   - Ported changes to match master (Execution of the resize hack has been moved to OnBrowserWasHidden)
      
**How Has This Been Tested?**  
   - This was tested with the CefSharp minimal example, creating multiple browsers (at least 6 are needed) and toggling the visibility of the browsers.
   - OS: Win10, x64

**Types of changes**
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Updated documentation

2022-11-20 23:58 UTC, amaitland requested changes
Comments inline.

2022-11-20 23:58 UTC, amaitland commented on CefSharp.Wpf/ChromiumWebBrowser.cs
> +                    if (EnableResizeHackForIssue2779)
This if statement should be moved up so the whole set of conditions is only evaluated if hack enabled.

2022-11-20 23:58 UTC, amaitland commented on CefSharp.Wpf/ChromiumWebBrowser.cs
> +            if (EnableResizeHackForIssue2779)
Remove this if statement, method needs to only be called if enabled.

2022-11-20 23:58 UTC, amaitland commented on CefSharp.Wpf/ChromiumWebBrowser.cs
> +                    await CefUiThreadRunAsync(async () =>
Let's remove the async modifier from the method and discard the Task returned from the method. 

There's no continuation.

2022-12-01 06:39 UTC, Wupval commented
@amaitland Is there an error in the code or any other reason the build seems to always fail?

2022-12-04 03:44 UTC, amaitland commented
Build failure is unrelated to this PR.

2022-12-13 02:02 UTC, merged

2022-12-13 02:19 UTC, amaitland commented
Follow up commit https://github.com/cefsharp/CefSharp/commit/0131dd8a331a3f500cf1c06da2b85307e9fc6de5

Properties have been renamed, no longer reference issue #2779, directly reference the upstream issue.

2022-12-13 02:25 UTC, amaitland commented
This is a greatly simplified version of the resize hack originally used. If anyone experiences any issues then I suggest you override `OnBrowserWasHidden` and `OnPaint` to implement your own version.

Original version for reference https://github.com/cefsharp/CefSharp/commit/9140c08a34e113b8865a80a7ac9f8b4aa19631c4